### ISSUE TITLE
BN001 | "manifests" folder not recognized as valid

### ISSUE THREAD

**Issue by dotNetkow** [apigeecs/bundle-linter#108]
Running the linter against any current Apigee proxy or shared flow bundle generates an error:

**Unexpected folder found "manifests"...**

This is a valid folder though, which contains just one XML file, manifest.xml. Most likely this is a newer Apigee change, visible when downloading a proxy revision.

**Comment by apetrosian** [comment]
@dotNetkow thanks for your contribution. It's now updated on `npm` with version `0.2.3`
