### ISSUE TITLE
Incorrect behavior when path value provided to -s option does not end in "apiproxy"

### ISSUE THREAD

**Issue by kurtkanaskie** [apigeecs/bundle-linter#110]
The -s option requires path to end in "apiproxy" otherwise behavior is misleading, validates policies and shows: " No apiproxy folder found in:... ".

To reproduce rename apiproxy to apiproxy1 and run apigeelint.

**Comment by davidwallen** [comment]
"apiproxy" is the folder name generated and required for a correct bundle.  While we could support a nonstandard naming convention and still lint, that bundle when zipped and deployed would fail with a "Bundle is Invalid" message.

I will however modify the -s / --path flag to accept a root folder, which can be searched for matching folders underneath that contain apiproxy folders.
