### ISSUE TITLE
Tagging support required for v0.2.3

### ISSUE THREAD

**Issue by mchidhambaram** [apigeecs/bundle-linter#115]
Last month we had installed Apigeelint v0.2.3 through npm. Couple of our developer installed npm module in local with higher version today causing version conflict due to recent change in the master branch now. Also, we don't have a way to get the earlier versions. Any help would be appreciated.

**Comment by apetrosian** [comment]
Hi @mchidhambaram,

You can specify which version of **apigeelint** you want to install:

`npm install apigeelint@0.2.3`

or directly specify in `package.json`
```json
"devDependencies": {
   "apigeelint": "0.2.3"
}
```

However, I would recommend ti stick with the latest version of linter.

**Comment by mchidhambaram** [comment]
Thanks a lot @apetrosian it works.
