### ISSUE TITLE
Enhance bundle-linter

### ISSUE THREAD

**Issue by SnehansuBhuyan** [apigeecs/bundle-linter#126]
Are the below capabilities are extendable by Apigee Lint ? 
- Sharedflow are in correct place in Proxy
-KVM Naming Convention
-API aesthetics
If not can I enhance the code as per my review checklist ? please confirm.

**Comment by ssvaidyanathan** [comment]
@SnehansuBhuyan - not sure what you mean by Sharedflow are in correct place ? As you know this is a linter and runs static rules, it does not go by any functional check. Placing the Sharedflow to the proxy depends on the logic. Same thing applies for API aesthetics as well.

You are more than welcome to contribute. But it has to be generic enough that will be useful to others

**Comment by SnehansuBhuyan** [comment]
@ssvaidyanathan - lets say I have two shared flow, one is Generate Request Tracking and Request-logging .I want Request tracking shared flow should come before Request-logging SF in API proxy. If the developer is put the SF sequence is incorrect , then my build-linter will the bundle-lint plugin will say 'correct the SF sequence.  
Hope you got my above question....can we implement this scenario in lint ? if yes, then please suggest where I need to be enhanced.

**Comment by ssvaidyanathan** [comment]
Thanks for clarifying

This is a functional issue. I dont think it needs to be in this plugin. This is a static code analyzer and does not involve any business logic check. 

If you need something like that - you need to script something custom and apply that on your CI/CD process so that it fails the build

**Comment by SnehansuBhuyan** [comment]
Thank you @ssvaidyanathan for clarifying.
I have another question, We created a checklist for KVM/target naming convention . As of today we are doing manually verifying the  KVM/target standard as per the checklist. Can we add those kvm/target naming conventions  in bundle-linter for automated review ?

**Comment by ssvaidyanathan** [comment]
We can as long as they are generic. Many customers I know use their own naming conventions that matches their team, business units, etc. So I would like to see your pattern and see if its generic enough to be put in there

**Comment by SnehansuBhuyan** [comment]
Sure @ssvaidyanathan . Can I get your emailID, so that I can send you the naming conventions patterns.

**Comment by ssvaidyanathan** [comment]
Appreciate if we could discuss here
