### ISSUE TITLE
"wsdl" folder not recognized as valid

### ISSUE THREAD

**Issue by mdharshad** [apigeecs/bundle-linter#135]
Running the linter against any current Apigee proxy generates an error:
Unexpected folder found "wsdl"...
This is a valid folder though, which contains just one WSDL file, product.wsdl. Folder is created by Apigee when implementing a policy for SOAP Message Validation.

**Comment by apetrosian** [comment]
Confirmed in `0.2.7`

Actual: BN001: Unexpected folder found "wsdl". Current root:"/apiproxy/resources/wsdl"

Expected: `/apiproxy/resources/wsdl` should be a valid folder, contains WSDL files

**Comment by apetrosian** [comment]
Fix available in `0.2.8`

**Comment by mdharshad** [comment]
Thanks for quickly resolving it...
