### ISSUE TITLE
Add test automation and coverage

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/bundle-linter#28]
We are using Codacy for this project, add test coverage and automation to the Codacy configuration.

Add NPM test support to the package.json.

**Comment by davidwallen** [comment]
https://github.com/codacy/node-codacy-coverage#installation

**Comment by davidwallen** [comment]
istanbul added, working on coverage integration to Codacy.

**Comment by gregswindle** [comment]
Hi @davidwallen, I'm willing to help with this issue in some capacity. First, however, may I suggest two tasks to be completed beforehand?

- [ ] 1. Add `mocha` as a devDepndency. I believe your team is testing with mocha as a globally installed dependency.
- [ ] 2. Move all fixtures into a new `test/fixtures` directory. There currently four or five specs that depend on resources on your Mac's HD, and it's impossible to speculate or recreate those resources. 
- [ ] 3. Commit and push those changes.

Once done, I can either submit a PR or review yours. Thanks!

**Comment by davidwallen** [comment]
Agreed Greg. @apetrosian
