### ISSUE TITLE
PO007 | Policy Naming Conventions - type indication

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/bundle-linter#43]
It is recommended that the policy name include an indicator of the policy type.

**Comment by ssvaidyanathan** [comment]
would be nice if the plugin reads a config file that has the convention names marked. We can leave it with some defaults.. but the values needs to be updated, they can update the config file and the rule  checks happen accordingly.

**Comment by davidwallen** [comment]
See https://github.com/apigeecs/bundle-linter/issues/77
