### ISSUE TITLE
New Plugin - Non Distributed Quota

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/bundle-linter#67]
An API Proxy request can be served by one or more distributed Edge components called Message Processors. If there are multiple Message Processors configured for serving API requests, then the quota will likely be exceeded because each Message Processor keeps it’s own ‘count’ of the requests it processes.

Consider, setting the <Distributed> element to true in the Quota policy to ensure that a common counter is used to track the API requests across all Message Processors.

**Comment by davidwallen** [comment]
PO022 Created.

**Comment by richarst** [comment]
The wording is goofy... it is a best practice to have distributed set to true, and synchronous set to false, there are scenarios where you may want the quota to not be distributed in this case it would act like a bucket style traffic limiter versus an allowance based system
