### ISSUE TITLE
Add configuration options (with defaults) to plugin metadata. 

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/bundle-linter#77]
Allow command line and config file access to options of the form:
BN006.limit=125 would set 

- the limit parameter for # of policies when executing rule BN006
- Implement via a config subobject on the metadata of form config.limit, config.attribute, etc.
- Plugins that expose a config method would be passed an object of field value pairs to initialize with - the config object can be a subset of exposed config attributes.

**Comment by endemics** [comment]
Could this also allow disabling specific plugins with something like PO007.enable=false? As far as I can tell there is currently no (documented) way to disable a specific plugin.

**Comment by apetrosian** [comment]
#127
