### ISSUE TITLE
Regression - No longer detecting unattached policies, FL001 not working

### ISSUE THREAD

**Issue by kurtkanaskie** [apigeecs/bundle-linter#87]
0.1.6 was reporting BN005, PO001, PO003, but no longer.

FL001 reporting 6 unconditional flows, there is only one, the "catch all". See attached.
[apiproxy.zip](https://github.com/apigeecs/bundle-linter/files/1297749/apiproxy.zip)

**Comment by apetrosian** [comment]
I can confirm that **BN005 - Unattached Policies** no longer detecting in `0.1.8`

**Comment by apetrosian** [comment]
@kurtkanaskie thanks for reporting the issue.

@davidwallen seems like we already have a fix here: https://github.com/apigeecs/bundle-linter/commit/00e143bb4c31d88d1adcb08fe170877a78542cec, but npm haven't this commit, could you publish it?

**Comment by apetrosian** [comment]
Published in version `0.2.0`
