### ISSUE TITLE
Exit code is always 0, should return 1 when there are errors

### ISSUE THREAD

**Issue by kurtkanaskie** [apigeecs/bundle-linter#91]
After running on command line, echo $? always returns 0 even if there are errors. This prevents apigeelint from being used in CI/CD to detect errors.

**Comment by gosunilgo** [comment]
I've committed a fix for non-zero return on test error - 6a87a5b06bebc6a7762a7ad40a702574c6e74e7d

This contains @tom-ashe fix   #90

**Comment by davidwallen** [comment]
Please confirm this fix Kurt. Looked good to me, would like your review on the merge.
